env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Build"
  timeout_in: 180m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Sync_script:
      - curl -sL https://github.com/youssefnone/cr/raw/circleci-project-setup/download.sh | bash
